test:
  #  hostport: httpbin.org:80
  #  hostport: localhost:5000
  #  uri: http://${test.hostport}
  uri: lb://httpbin


spring:
  application:
    name: juejin-gateway
  jmx:
    enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
#      - PrefixPath=/httpbin
      - AddResponseHeader=X-Response-Default-Foo, Default-Bar
      routes:
      - id: default_path_to_httpbin
        uri: ${test.uri}
        order: 10000
        predicates:
        - Path=/**
      - id: order
        uri:  lb://order-service
        predicates:
          - Path=/order/**
#order-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.ZoneAvoidanceRule

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

management.endpoints.web.exposure.include: '*'


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

